services:
  app:
    image: somethinghere
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/vendor
  
  database:
    image: postgres:18.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
