services:
  backend:
    image: crunchypandesal/aralith-php:dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/vendor
    env_file:
      - .env

  frontend:
    image: crunchypandesal/aralith-vite:dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  database:
    image: postgres:18.4
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
